# Unit 1 - Introduction to tensors with PyTorch

Fundamentally, deep learning is applied mathematics. While some of the math is fairly complex and verbose, the basic building block that enables programmatic deep learning in libraries like PyTorch is the _tensor_. 

Tensors are single or multi-dimensional matrices on which we perform the mathematical operations that make deep learning possible. To create a tensor, we can use PyTorch's `torch.tensor` method.

In [3]:
import torch

tensor = torch.tensor([0])

print(tensor)

tensor([0])

Notice that in the example above, we created a tensor from a Python list that had 1 element. To create tensors with more dimensions, we can use lists with more elements or nested lists.

In [6]:
three_element_tensor = torch.tensor([0,1,2])
multidim_tensor = torch.tensor([[0,1],[2,3],[4,5]])

print(f"Tensor with 3 elements:\n {three_element_tensor}")
print(f"Tensor with more than 1 dimension:\n {multidim_tensor}")

Tensor with 3 elements:
 tensor([0, 1, 2])
Tensor with more than 1 dimension:
 tensor([[0, 1],
        [2, 3],
        [4, 5]])


If you've used matrices and arrays in Python before, you might notice these look very similar to _NumPy arrays_. NumPy is a very popular library for working with matrices and arrays in Python, and provides the building blocks for data manipulation libraries such as Pandas.

In [8]:
import numpy as np

array = np.array([0])
print(array)

[0]


In fact, PyTorch even provides methods to create tensors directly from NumPy arrays - and even allows them to share the same memory location!

In [9]:
tensor_from_numpy = torch.from_numpy(array)

print(tensor_from_numpy)

tensor([0])


Woohoo! Of course, right around now you might be wondering, _what's the difference? Why do we even need NumPy_? 

Great questions honestly. 